# .github/workflows/batch-generate-devotionals.yml
name: 🚀 Batch Generate Devotionals

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to generate (1-365)'
        required: true
        default: '30'
        type: string
      start_date:
        description: 'Start date (YYYY-MM-DD) - leave empty for today'
        required: false
        type: string

jobs:
  batch-generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: 📦 Install dependencies
      run: |
        npm init -y
        npm install axios moment
    
    - name: ⚡ Validate inputs
      run: |
        DAYS="${{ github.event.inputs.days }}"
        if ! [[ "$DAYS" =~ ^[1-9][0-9]*$ ]] || [ "$DAYS" -gt 365 ]; then
          echo "❌ Invalid days input. Must be 1-365"
          exit 1
        fi
        echo "✅ Will generate $DAYS devotionals"
    
    - name: 🎯 Batch generate devotionals
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DAYS_TO_GENERATE: ${{ github.event.inputs.days }}
        START_DATE: ${{ github.event.inputs.start_date }}
      run: |
        cat > batch_generate.js << 'EOF'
        const axios = require('axios');
        const fs = require('fs');
        const moment = require('moment');
        
        // Enhanced coffee facts database
        const coffeeFacts = [
          "Coffee was first discovered in Ethiopia over 1,000 years ago by a goat herder named Kaldi who noticed his goats became energetic after eating coffee berries.",
          "Coffee is the world's second-most traded commodity after oil, with over 25 million families worldwide depending on coffee for their livelihood.",
          "The word 'coffee' comes from the Arabic word 'qahwah,' which originally meant 'wine of the bean.'",
          "A single coffee tree can live and produce coffee for over 100 years, with some trees in Yemen being over 200 years old.",
          "Coffee beans are actually seeds from coffee cherries, and each cherry typically contains two seeds.",
          "The perfect water temperature for brewing coffee is between 195-205°F (90-96°C) to extract optimal flavors without burning.",
          "Finland consumes the most coffee per capita in the world, with each person drinking about 12 kilograms per year.",
          "Coffee was originally eaten, not drunk. Ancient Ethiopian tribes mixed coffee berries with animal fat for energy during long journeys.",
          "The most expensive coffee in the world is Kopi Luwak, made from beans that have been eaten and excreted by Asian palm civets.",
          "Instant coffee was invented in 1901 by Japanese scientist Satori Kato, revolutionizing coffee consumption worldwide.",
          "Coffee can improve physical performance by increasing adrenaline levels by up to 12%.",
          "A single coffee tree produces only 1-2 pounds of roasted coffee per year, requiring about 2,000 cherries.",
          "Used coffee grounds make excellent fertilizer for plants, adding nitrogen and improving soil drainage.",
          "The term 'cup of joe' may come from Josephus Daniels, a US Navy Secretary who banned alcohol on ships in 1914.",
          "Coffee stays fresh for about 2-4 weeks after roasting when stored in an airtight container away from light.",
          "The first webcam was invented to monitor a coffee pot at Cambridge University in 1991.",
          "Coffee houses were called 'Schools of the Wise' in the Ottoman Empire because of the intellectual discussions held there.",
          "Brazil produces about one-third of the world's coffee, making it the largest coffee producer globally.",
          "Espresso means 'pressed out' in Italian, referring to the brewing method of forcing hot water through finely ground coffee.",
          "Coffee loses approximately 70% of its flavor within two minutes of being ground if not brewed immediately."
        ];
        
        // Expanded scripture database
        const scriptures = [
          { verse: "Psalm 23:5", text: "You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows." },
          { verse: "Isaiah 40:31", text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint." },
          { verse: "Philippians 4:13", text: "I can do all this through him who gives me strength." },
          { verse: "Matthew 11:28", text: "Come to me, all you who are weary and burdened, and I will give you rest." },
          { verse: "Jeremiah 29:11", text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, to give you hope and a future." },
          { verse: "Psalm 46:10", text: "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth." },
          { verse: "Proverbs 3:5-6", text: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight." },
          { verse: "Romans 8:28", text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose." },
          { verse: "1 Corinthians 10:31", text: "So whether you eat or drink or whatever you do, do it all for the glory of God." },
          { verse: "Psalm 118:24", text: "This is the day the Lord has made; let us rejoice and be glad in it." },
          { verse: "2 Corinthians 12:9", text: "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.'" },
          { verse: "Joshua 1:9", text: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go." },
          { verse: "Psalm 27:1", text: "The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid?" },
          { verse: "1 Peter 5:7", text: "Cast all your anxiety on him because he cares for you." },
          { verse: "Ephesians 2:10", text: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do." }
        ];
        
        async function batchGenerate() {
          const daysToGenerate = parseInt(process.env.DAYS_TO_GENERATE) || 30;
          const startDate = moment(process.env.START_DATE || moment().format('YYYY-MM-DD'));
          
          console.log(`🚀 Starting batch generation of ${daysToGenerate} devotionals`);
          console.log(`📅 Starting from: ${startDate.format('YYYY-MM-DD')}`);
          
          // Create devotionals directory
          if (!fs.existsSync('devotionals')) {
            fs.mkdirSync('devotionals', { recursive: true });
          }
          
          let generated = 0;
          let skipped = 0;
          
          for (let i = 0; i < daysToGenerate; i++) {
            const currentDate = startDate.clone().add(i, 'days');
            const dateString = currentDate.format('YYYY-MM-DD');
            const filePath = `devotionals/${dateString}.json`;
          fs.writeFileSync(filePath, JSON.stringify(fallback, null, 2));
          console.log(`🚨 Created fallback devotional for ${dateString}`);
        }
        
        // Run batch generation
        batchGenerate().catch(error => {
          console.error('💥 Fatal error in batch generation:', error);
          process.exit(1);
        });
        EOF
        
        # Execute the batch generation
        node batch_generate.js
    
    - name: 📝 Commit all new devotionals
      run: |
        git config --local user.email "hebrews-bot@github.com"
        git config --local user.name "HeBrews Batch Bot ☕"
        
        # Add all devotional files
        git add devotionals/
        
        # Check if there are changes
        if git diff --staged --quiet; then
          echo "No new devotional files to commit"
        else
          DAYS="${{ github.event.inputs.days }}"
          START_DATE="${{ github.event.inputs.start_date }}"
          ACTUAL_START=$(echo ${START_DATE:-$(date +%Y-%m-%d)})
          
          git commit -m "🚀 Batch generate $DAYS devotionals starting from $ACTUAL_START
          
          🤖 Auto-generated by HeBrews Batch Bot
          ☕ Ready for mobile app consumption
          📱 Users now have $DAYS days of fresh content"
          
          git push
          echo "✅ Successfully committed and pushed $DAYS devotionals"
        fi
    
    - name: 📊 Final Summary
      run: |
        echo "🎉 Batch generation complete!"
        echo "📚 Generated devotionals for ${{ github.event.inputs.days }} days"
        echo "📱 Your HeBrews iOS app is now loaded with fresh content"
        echo "☕ Users will have daily devotionals automatically"
        echo ""
        echo "Next steps:"
        echo "1. Daily devotionals will auto-generate at 6 AM UTC"
        echo "2. Your iOS app will fetch new content automatically"
        echo "3. Users get fresh devotionals every day"/${dateString}.json`;
            
            // Skip if file already exists
            if (fs.existsSync(filePath)) {
              console.log(`⏭️  Skipping ${dateString} - already exists`);
              skipped++;
              continue;
            }
            
            try {
              await generateSingleDevotional(dateString, currentDate);
              generated++;
              console.log(`✅ Generated devotional ${generated}/${daysToGenerate - skipped} for ${dateString}`);
              
              // Rate limiting - wait 2 seconds between API calls
              if (i < daysToGenerate - 1) {
                await new Promise(resolve => setTimeout(resolve, 2000));
              }
              
            } catch (error) {
              console.error(`❌ Failed to generate devotional for ${dateString}:`, error.message);
              
              // Create fallback
              createFallbackDevotional(dateString, currentDate);
              generated++;
            }
          }
          
          console.log(`\n🎉 Batch generation complete!`);
          console.log(`✅ Generated: ${generated} devotionals`);
          console.log(`⏭️  Skipped: ${skipped} devotionals (already existed)`);
          console.log(`📱 Your HeBrews app now has ${generated + skipped} devotionals ready!`);
        }
        
        async function generateSingleDevotional(dateString, momentDate) {
          // Select items ensuring variety
          const coffeeFactIndex = momentDate.dayOfYear() % coffeeFacts.length;
          const scriptureIndex = momentDate.dayOfYear() % scriptures.length;
          
          const coffeeFact = coffeeFacts[coffeeFactIndex];
          const scripture = scriptures[scriptureIndex];
          
          // Determine season and special occasions
          const season = getSeason(momentDate.dayOfYear());
          const dayOfWeek = momentDate.format('dddd');
          const isWeekend = momentDate.day() === 0 || momentDate.day() === 6;
          
          const prompt = `Create a Christian devotional for ${dayOfWeek}, ${dateString} (${season}).
          
          Coffee Fact: "${coffeeFact}"
          Scripture: ${scripture.verse} - "${scripture.text}"
          Context: ${isWeekend ? 'Weekend reflection time' : 'Weekday encouragement'}
          
          Requirements:
          1. Title: 4-8 words, inspiring, connects coffee and faith
          2. Devotional Text: 180-220 words connecting coffee fact to scripture meaningfully
          3. Reflection Question: Personal, thought-provoking
          4. Prayer: 2-3 sentences, heartfelt and relevant
          
          Style: Warm, encouraging, authentic, practical for daily Christian living.
          
          Respond with ONLY valid JSON:
          {
            "title": "...",
            "devotional_text": "...", 
            "reflection_question": "...",
            "prayer": "..."
          }`;
          
          const response = await axios.post('https://api.openai.com/v1/chat/completions', {
            model: 'gpt-4o-mini',
            messages: [
              {
                role: 'system',
                content: 'You are an experienced Christian devotional writer who creates meaningful daily content that authentically blends coffee culture with biblical wisdom.'
              },
              {
                role: 'user',
                content: prompt
              }
            ],
            max_tokens: 600,
            temperature: 0.7
          }, {
            headers: {
              'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
              'Content-Type': 'application/json'
            }
          });
          
          // Parse response
          const aiContent = response.data.choices[0].message.content;
          const jsonMatch = aiContent.match(/\{[\s\S]*\}/);
          
          if (!jsonMatch) {
            throw new Error('No valid JSON in AI response');
          }
          
          const aiData = JSON.parse(jsonMatch[0]);
          
          // Create final devotional
          const devotional = {
            date: dateString,
            title: aiData.title,
            coffee_fact: coffeeFact,
            scripture: scripture,
            devotional_text: aiData.devotional_text,
            reflection_question: aiData.reflection_question,
            prayer: aiData.prayer,
            audio_url: null
          };
          
          // Validate
          validateDevotional(devotional);
          
          // Save
          const filePath = `devotionals/${dateString}.json`;
          fs.writeFileSync(filePath, JSON.stringify(devotional, null, 2));
        }
        
        function getSeason(dayOfYear) {
          if (dayOfYear >= 355 || dayOfYear <= 79) return 'Winter';
          if (dayOfYear >= 80 && dayOfYear <= 171) return 'Spring';
          if (dayOfYear >= 172 && dayOfYear <= 265) return 'Summer';
          return 'Fall';
        }
        
        function validateDevotional(devotional) {
          const required = ['date', 'title', 'coffee_fact', 'scripture', 'devotional_text', 'reflection_question', 'prayer'];
          for (const field of required) {
            if (!devotional[field]) {
              throw new Error(`Missing required field: ${field}`);
            }
          }
          
          if (devotional.devotional_text.length < 100) {
            throw new Error('Devotional text too short');
          }
        }
        
        function createFallbackDevotional(dateString, momentDate) {
          const fallback = {
            date: dateString,
            title: "Faith and Coffee Journey",
            coffee_fact: coffeeFacts[momentDate.dayOfYear() % coffeeFacts.length],
            scripture: scriptures[momentDate.dayOfYear() % scriptures.length],
            devotional_text: "Each morning presents us with new opportunities to experience God's goodness, much like each cup of coffee offers a fresh start to our day. God's mercies are new every morning, and His love for us never changes. As we begin this day, let's remember that we can find strength and joy in both the simple pleasures of life and the profound love of our Creator.",
            reflection_question: "How can you find God's presence in the simple moments of today?",
            prayer: "Lord, thank You for this new day and for Your constant love. Help me to see You in both the ordinary and extraordinary moments. Amen.",
            audio_url: null
          };
          
          const filePath = `devotionals
