# .github/workflows/generate-daily-devotional.yml
name: 🤖 Generate Daily Devotional

on:
  # Runs daily at 6:00 AM UTC (adjust timezone as needed)
  schedule:
    - cron: '0 6 * * *'
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      date:
        description: 'Date for devotional (YYYY-MM-DD) - leave empty for today'
        required: false
        type: string

jobs:
  generate-devotional:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: 📦 Install dependencies
      run: |
        npm init -y
        npm install axios moment cheerio
    
    - name: 🎯 Generate today's devotional
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TARGET_DATE: ${{ github.event.inputs.date }}
      run: |
        cat > generate_devotional.js << 'EOF'
        const axios = require('axios');
        const fs = require('fs');
        const moment = require('moment');
        
        // Coffee facts database
        const coffeeFacts = [
          "Coffee was first discovered in Ethiopia over 1,000 years ago by a goat herder named Kaldi.",
          "Coffee is the world's second-most traded commodity after oil.",
          "The word 'coffee' comes from the Arabic word 'qahwah,' meaning 'wine of the bean.'",
          "A coffee tree can live and produce coffee for over 100 years.",
          "Coffee beans are actually seeds from coffee cherries, not beans at all.",
          "The perfect water temperature for brewing coffee is between 195-205°F (90-96°C).",
          "Finland consumes the most coffee per capita in the world - about 12kg per person per year.",
          "Coffee was originally eaten, not drunk. Early tribes mixed coffee berries with fat for energy.",
          "The most expensive coffee in the world is Kopi Luwak, made from beans eaten and excreted by civets.",
          "Instant coffee was invented in 1901 by Japanese scientist Satori Kato.",
          "Coffee can help improve physical performance by increasing adrenaline levels.",
          "A single coffee tree produces only about 1-2 pounds of coffee per year.",
          "Coffee grounds can be used as a natural fertilizer for plants.",
          "The term 'cup of joe' may come from Josephus Daniels, a US Navy Secretary who banned alcohol on ships.",
          "Coffee stays fresh for about 2 weeks after roasting when stored properly."
        ];
        
        // Scripture database for rotation
        const scriptures = [
          {
            verse: "Psalm 23:5",
            text: "You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows."
          },
          {
            verse: "Isaiah 40:31",
            text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint."
          },
          {
            verse: "Philippians 4:13",
            text: "I can do all this through him who gives me strength."
          },
          {
            verse: "Matthew 11:28",
            text: "Come to me, all you who are weary and burdened, and I will give you rest."
          },
          {
            verse: "Jeremiah 29:11",
            text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, to give you hope and a future."
          },
          {
            verse: "Psalm 46:10",
            text: "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth."
          },
          {
            verse: "Proverbs 3:5-6",
            text: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight."
          },
          {
            verse: "Romans 8:28",
            text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose."
          },
          {
            verse: "1 Corinthians 10:31",
            text: "So whether you eat or drink or whatever you do, do it all for the glory of God."
          },
          {
            verse: "Psalm 118:24",
            text: "This is the day the Lord has made; let us rejoice and be glad in it."
          }
        ];
        
        async function generateDevotional() {
          // Determine target date
          const targetDate = process.env.TARGET_DATE || moment().format('YYYY-MM-DD');
          const filePath = `devotionals/${targetDate}.json`;
          
          console.log(`🎯 Generating devotional for ${targetDate}`);
          
          // Check if devotional already exists
          if (fs.existsSync(filePath)) {
            console.log(`✅ Devotional for ${targetDate} already exists`);
            return;
          }
          
          // Create devotionals directory if needed
          if (!fs.existsSync('devotionals')) {
            fs.mkdirSync('devotionals', { recursive: true });
          }
          
          try {
            // Select random coffee fact and scripture
            const coffeeFact = coffeeFacts[Math.floor(Math.random() * coffeeFacts.length)];
            const scripture = scriptures[Math.floor(Math.random() * scriptures.length)];
            
            // Get day of year for seasonal themes
            const dayOfYear = moment(targetDate).dayOfYear();
            const season = getSeason(dayOfYear);
            
            // Generate with OpenAI
            const prompt = `Create an inspiring Christian devotional for ${targetDate} that combines faith and coffee themes.
            
            Season: ${season}
            Coffee Fact to incorporate: "${coffeeFact}"
            Scripture: ${scripture.verse} - "${scripture.text}"
            
            Create a devotional with these requirements:
            1. Title: Inspiring and relevant to both coffee and faith (4-8 words)
            2. Devotional Text: 180-220 words connecting the coffee fact to the scripture meaningfully
            3. Reflection Question: Thought-provoking question for personal contemplation
            4. Prayer: 2-3 sentence prayer related to the theme
            
            Make it encouraging, authentic, and practically applicable to daily Christian life.
            Tone: Warm, encouraging, conversational but reverent.
            
            Respond with ONLY a JSON object in this exact format:
            {
              "title": "...",
              "devotional_text": "...",
              "reflection_question": "...",
              "prayer": "..."
            }`;
            
            const response = await axios.post('https://api.openai.com/v1/chat/completions', {
              model: 'gpt-4o-mini',
              messages: [
                {
                  role: 'system',
                  content: 'You are a Christian devotional writer who creates meaningful, encouraging daily devotionals that blend coffee culture with biblical wisdom.'
                },
                {
                  role: 'user',
                  content: prompt
                }
              ],
              max_tokens: 600,
              temperature: 0.7
            }, {
              headers: {
                'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
                'Content-Type': 'application/json'
              }
            });
            
            // Parse AI response
            const aiContent = response.data.choices[0].message.content;
            let aiData;
            
            try {
              // Extract JSON from response
              const jsonMatch = aiContent.match(/\{[\s\S]*\}/);
              if (jsonMatch) {
                aiData = JSON.parse(jsonMatch[0]);
              } else {
                throw new Error('No JSON found in response');
              }
            } catch (parseError) {
              console.log('⚠️ AI response parsing failed, using fallback');
              aiData = createFallbackContent(coffeeFact, scripture);
            }
            
            // Construct final devotional
            const devotional = {
              date: targetDate,
              title: aiData.title || `Faith and Coffee - ${targetDate}`,
              coffee_fact: coffeeFact,
              scripture: scripture,
              devotional_text: aiData.devotional_text || createFallbackDevotional(coffeeFact, scripture),
              reflection_question: aiData.reflection_question || "How can you apply today's message to your daily walk with God?",
              prayer: aiData.prayer || "Lord, thank You for Your daily mercies. Help me to grow in faith and love today. Amen.",
              audio_url: null
            };
            
            // Validate required fields
            const requiredFields = ['date', 'title', 'coffee_fact', 'scripture', 'devotional_text', 'reflection_question', 'prayer'];
            for (const field of requiredFields) {
              if (!devotional[field]) {
                throw new Error(`Missing required field: ${field}`);
              }
            }
            
            // Write to file
            fs.writeFileSync(filePath, JSON.stringify(devotional, null, 2));
            console.log(`✅ Successfully generated devotional for ${targetDate}`);
            console.log(`📖 Title: ${devotional.title}`);
            
          } catch (error) {
            console.error('❌ Error generating devotional:', error.message);
            
            // Create emergency fallback
            const fallbackDevotional = createEmergencyFallback(targetDate);
            fs.writeFileSync(filePath, JSON.stringify(fallbackDevotional, null, 2));
            console.log('🚨 Created emergency fallback devotional');
          }
        }
        
        function getSeason(dayOfYear) {
          if (dayOfYear >= 355 || dayOfYear <= 79) return 'Winter';
          if (dayOfYear >= 80 && dayOfYear <= 171) return 'Spring';
          if (dayOfYear >= 172 && dayOfYear <= 265) return 'Summer';
          return 'Fall';
        }
        
        function createFallbackContent(coffeeFact, scripture) {
          return {
            title: "Daily Bread and Coffee",
            devotional_text: `Just as we start our day with coffee to awaken our senses, God invites us to begin each morning with His Word to awaken our spirits. ${coffeeFact} Similarly, God's love and faithfulness have been constant throughout history. When we read "${scripture.text}" from ${scripture.verse}, we're reminded that God prepares good things for us each day. Let your morning coffee be a reminder that God's mercies are new every morning, and His love never fails.`,
            reflection_question: "How can you make your morning routine a time of connection with God?",
            prayer: "Heavenly Father, as I enjoy this coffee, help me to savor Your presence even more. Thank You for Your daily provision and love. Amen."
          };
        }
        
        function createEmergencyFallback(date) {
          return {
            date: date,
            title: "Morning Mercies",
            coffee_fact: "Coffee is enjoyed by over 2 billion people worldwide every day.",
            scripture: {
              verse: "Lamentations 3:22-23",
              text: "Because of the Lord's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness."
            },
            devotional_text: "Each morning brings new opportunities to experience God's faithfulness. Just as coffee provides energy for our physical bodies, God's Word energizes our souls. His mercies are fresh each day, never stale or depleted. As you sip your morning coffee, remember that God's love for you is constant and His plans for you are good.",
            reflection_question: "What are you most grateful for as you begin this new day?",
            prayer: "Lord, thank You for the gift of this new day. Help me to trust in Your goodness and walk in Your ways. Amen.",
            audio_url: null
          };
        }
        
        // Run the generation
        generateDevotional().catch(error => {
          console.error('Fatal error:', error);
          process.exit(1);
        });
        EOF
        
        # Execute the script
        node generate_devotional.js
    
    - name: 📝 Commit and push new devotional
      run: |
        git config --local user.email "hebrews-bot@github.com"
        git config --local user.name "HeBrews Bot ☕"
        
        # Add any new devotional files
        git add devotionals/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No new devotional files to commit"
        else
          DATE=$(date +%Y-%m-%d)
          git commit -m "✨ Add daily devotional for $DATE
          
          🤖 Auto-generated by HeBrews Bot
          ☕ Fresh devotional content ready for mobile app"
          
          git push
          echo "✅ Successfully committed and pushed new devotional"
        fi
    
    - name: 📊 Summary
      run: |
        echo "🎉 Daily devotional generation complete!"
        echo "📱 Your iOS app will automatically fetch the new content"
        echo "☕ HeBrews users will have fresh devotional content"
